peer lifecycle chaincode commit \
    -o orderer-org0:7050 \
    --channelID mychannel \
    --name uc4-cc \
    --version 1.0 \
    --sequence 1 \
    --tls \
    --cafile /tmp/secrets/tls-ca/cert.pem \
    --peerAddresses peer1-org1:7051 \
    --tlsRootCertFiles /tmp/secrets/tls-ca/cert.pem  \
    --peerAddresses peer1-org2:7051 \
    --tlsRootCertFiles /tmp/secrets/tls-ca/cert.pem  \
    --collections-config /tmp/hyperledger/chaincode/collections_config.json
