apiVersion: apps/v1
kind: Deployment
metadata:
    name: ca-tls
    labels:
        app: ca-tls-root
spec:
    selector:
        matchLabels:
            app: ca-tls-root
    template:
        metadata: 
            labels:
                app: ca-tls-root
        spec:
            containers:
              - name: ca-tls
                image: hyperledger/fabric-ca
                command: ["fabric-ca-server", "start", "-b", "tls-ca-admin:tls-ca-adminpw", "--port", "7052"]
                env:
                - name: FABRIC_CA_HOME
                  value: "/etc/hyperledger/fabric-ca-server"
                - name: FABRIC_CA_SERVER_TLS_ENABLED
                  value: "true"
                - name: FABRIC_CA_SERVER_CSR_CN
                  value: "ca-tls"
                - name: FABRIC_CA_SERVER_CSR_HOSTS
                  value: "0.0.0.0"
                - name: FABRIC_CA_SERVER_DEBUG
                  value: "true"

